package org.chiwooplatform.samples.entity;

import java.util.Date;

import org.springframework.data.annotation.Id;

import org.chiwooplatform.samples.support.DateTypeConverter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import lombok.Builder;
import lombok.Data;

@Data
@DynamoDBTable(tableName = ChatRoom.TABLE_NAME)
public class ChatRoom {

	public static final String TABLE_NAME = "ChatRoom";

	@Id
	@DynamoDBHashKey(attributeName = "name")
	private String name;
	@DynamoDBAttribute(attributeName = "description")
	private String description;
	@DynamoDBAttribute(attributeName = "recentMessageText")
	private String recentMessageText;
	@DynamoDBAttribute(attributeName = "recentMessageAuthor")
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "recentMessageAuthor-recentMessageDateTime-index")
	private String recentMessageAuthor;

	@DynamoDBAutoGeneratedTimestamp
	@DynamoDBTypeConverted(converter = DateTypeConverter.class)
	@DynamoDBAttribute(attributeName = "recentMessageDateTime")
	@DynamoDBIndexRangeKey(globalSecondaryIndexName = "recentMessageAuthor-recentMessageDateTime-index")
	private Date recentMessageDateTime;

	public ChatRoom() {
		super();
	}

	@Builder
	private ChatRoom(String name, String description, String recentMessageText,
			String recentMessageAuthor, Date recentMessageDateTime) {
		this.name = name;
		this.description = description;
		this.recentMessageText = recentMessageText;
		this.recentMessageAuthor = recentMessageAuthor;
		this.recentMessageDateTime = recentMessageDateTime;
	}

}
