/*
 * Copyright 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.chiwooplatform.samples.entity;

import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import java.time.Instant;

import org.chiwooplatform.samples.support.DateUtils;
import org.chiwooplatform.samples.support.InstantTimestampTypeConverter;
import org.chiwooplatform.samples.support.YearTypeConverter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import lombok.Data;

/**
 * User 앤티티는 아래와 같으며, HashKey는 "id" 속성으로 구성 된다.
 * 
 * <code>
{
  "id" : "scott",
  "name" : "scott, funny",
  "numberOfPlaylists" : 1,
  "joinDate" : 1502693425872,
  "joinYear" : 1483196400000,
  "leaveDate" : {
    "epochSecond" : 1502693437,
    "nano" : 119000000
  },
  "postCode" : "411012",
  "testSet" : [ "1", "2", "3" ]
}</code>
 *
 */
@Data
@DynamoDBTable(tableName = User.TABLE_NAME)
public class User {

	public static final String TABLE_NAME = "User";

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	private String name;

	private Integer numberOfPlaylists;

	private Date joinDate;

	@DynamoDBTypeConverted(converter = YearTypeConverter.class)
	private Date joinYear;

	@DynamoDBTypeConverted(converter = InstantTimestampTypeConverter.class)
	private Instant leaveDate;

	private String postCode;

	private Set<String> testSet;

	public User() {
		super();
	}

	private User(Builder builder) {
		this.id = builder.id;
		this.name = builder.name;
		this.numberOfPlaylists = builder.numberOfPlaylists;
		this.joinDate = builder.joinDate;
		this.joinYear = builder.joinYear;
		this.leaveDate = builder.leaveDate;
		this.postCode = builder.postCode;
		this.testSet = builder.testSet;
	}

	public static final class Builder {
		String id;
		String name;
		Integer numberOfPlaylists;
		Date joinDate;
		Date joinYear;
		Instant leaveDate;
		String postCode;
		Set<String> testSet;

		public static Builder create() {
			return new Builder();
		}

		public Builder id(String id) {
			this.id = id;
			return this;
		}

		public Builder name(String name) {
			this.name = name;
			return this;
		}

		public Builder numberOfPlaylists(Integer numberOfPlaylists) {
			this.numberOfPlaylists = numberOfPlaylists;
			return this;
		}

		public Builder joinDate() {
			Date now = DateUtils.now();
			this.joinDate = now;
			this.joinYear = now;
			return this;
		}

		public Builder leaveDate(Instant leaveDate) {
			this.leaveDate = leaveDate;
			return this;
		}

		public Builder postCode(String postCode) {
			this.postCode = postCode;
			return this;
		}

		public Builder testSet(Set<String> testSet) {
			this.testSet = testSet;
			return this;
		}

		public Builder testSet(String... testSet) {
			this.testSet = new HashSet<String>(Arrays.asList(testSet));
			return this;
		}

		public User build() {
			return new User(this);
		}
	}

}
